SET FOREIGN_KEY_CHECKS=0

DROP TABLE IF EXISTS `role` CASCADE
;

CREATE TABLE `role`
(
	`role_id` VARCHAR(32) NOT NULL,
	`role_name` VARCHAR(50),
	`role_description` VARCHAR(255),
	CONSTRAINT `PK_role` PRIMARY KEY (`role_id`)
)
;

SET FOREIGN_KEY_CHECKS=1
